export const environment = {
  production: true,
  firebaseConfig : {
    apiKey: 'YOUR_FIREBASE_DEVELOPMENT_PROJECT_APIKEY',
    authDomain: 'YOUR_FIREBASE_DEVELOPMENT_AUTH_DOMAIN',
    databaseURL: 'YOUR_FIREBASE_DEVELOPMENT_DATABASE_URL',
    projectId: 'YOUR_FIREBASE_DEVELOPMENT_PROJECT_ID',
    storageBucket: 'YOUR_FIREBASE_DEVELOPMENT_STORAGE_BUCKED',
    messagingSenderId: 'YOUR_FIREBASE_DEVELOPMENT_MESSAGING_SENDER_ID'
  }
};
