export const environment = {
  production: true,
  firebaseConfig : {
    apiKey: 'YOUR_FIREBASE_PRODUCTION_PROJECT_APIKEY',
    authDomain: 'YOUR_FIREBASE_PRODUCTION_AUTH_DOMAIN',
    databaseURL: 'YOUR_FIREBASE_PRODUCTION_DATABASE_URL',
    projectId: 'YOUR_FIREBASE_PRODUCTION_PROJECT_ID',
    storageBucket: 'YOUR_FIREBASE_PRODUCTION_STORAGE_BUCKED',
    messagingSenderId: 'YOUR_FIREBASE_PRODUCTION_MESSAGING_SENDER_ID',
    appId: 'YOUR_FIREBASE_PRODUCTION_APP_ID'
  }
};
